import assert from 'node:assert/strict';
import test from 'node:test';
import { OpenTradeService, type OpenTradePreview, type OpenTradeState, type PreviewStore } from '../src/trading/open-trade.js';
import type { ExchangeAdapter } from '@btc-arbitrage/exchange-core';

test('preview uses executable BBO and routes entry by cheapest maker first, then cheapest taker', async () => {
  const store = memoryStore(); const service = new OpenTradeService(registry(fakeAdapter('risex', '100010', '100020', '0.001'), fakeAdapter('extended', '99990', '100000', '0.0001')), store, options());
  const preview = await service.createPreview({ signalId: 1, symbol: 'BTCUSDT', marketType: 'perpetual', exchanges: ['risex', 'extended'] });
  assert.equal(preview.shortExchange, 'risex'); assert.equal(preview.longExchange, 'extended'); assert.equal(preview.limitExchange, 'extended'); assert.equal(preview.marketExchange, 'risex'); assert.equal(preview.quantityBase, '0.009');
});

test('preview uses taker fee as tie-breaker when maker fees are equal', async () => {
  const store = memoryStore(); const service = new OpenTradeService(registry(fakeAdapter('risex', '100010', '100020', '0.001'), fakeAdapter('extended', '99990', '100000', '0.0001')), store, { ...options(), fees: { risex: { makerBps: '0', takerBps: '1.5' }, extended: { makerBps: '0', takerBps: '2.5' }, arcus: { makerBps: '0', takerBps: '0' } } });
  const preview = await service.createPreview({ signalId: 1, symbol: 'BTCUSDT', marketType: 'perpetual', exchanges: ['risex', 'extended'] });
  assert.equal(preview.limitExchange, 'extended');
  assert.equal(preview.marketExchange, 'risex');
});

test('confirmation hedges only confirmed partial limit fills and protects from actual long fill', async () => {
  const store = memoryStore(); const risex = fakeAdapter('risex', '100010', '100020', '0.001'); const extended = fakeAdapter('extended', '99990', '100000', '0.0001', [{ status: 'partially_filled', filledQuantityBase: '0.004', averageFillPriceUsd: '100000' }, { status: 'filled', filledQuantityBase: '0.009', averageFillPriceUsd: '100000' }]);
  const service = new OpenTradeService(registry(risex, extended), store, { ...options(), sleep: async () => undefined, limitTimeoutMs: 1000 }); const p = await service.createPreview({ signalId: 1, symbol: 'BTCUSDT', marketType: 'perpetual', exchanges: ['risex', 'extended'] });
  await service.confirm(p.token);
  const marketOrders = risex.calls.filter(x => x.type === 'market'); assert.deepEqual(marketOrders.map(x => x.quantityBase), ['0.004', '0.005']);
  assert.equal(extended.calls.find(x => x.type === 'take-profit-market')?.triggerPriceUsd, '103000'); assert.equal(extended.calls.find(x => x.type === 'stop-market')?.triggerPriceUsd, '97000'); assert.equal(store.states.at(-1), 'open');
});

test('confirmation applies TP/SL percentages from configuration', async () => {
  const store = memoryStore(); const risex = fakeAdapter('risex', '100010', '100020', '0.001', [{ status: 'filled', filledQuantityBase: '0.009', averageFillPriceUsd: '100020' }]); const extended = fakeAdapter('extended', '99990', '100000', '0.0001');
  const service = new OpenTradeService(registry(risex, extended), store, { ...options(), takeProfitPercent: '10', stopLossPercent: '5', sleep: async () => undefined, limitTimeoutMs: 1000 }); const p = await service.createPreview({ signalId: 1, symbol: 'BTCUSDT', marketType: 'perpetual', exchanges: ['risex', 'extended'] });
  await service.confirm(p.token);
  assert.equal(extended.calls.find(x => x.type === 'take-profit-market')?.triggerPriceUsd, '110000');
  assert.equal(extended.calls.find(x => x.type === 'stop-market')?.triggerPriceUsd, '95000');
});

test('expired or repeated confirmation is rejected without orders', async () => { const store = memoryStore(); const service = new OpenTradeService(registry(fakeAdapter('risex','2','3','0.1'), fakeAdapter('extended','1','2','0.1')), store, { ...options(), now: () => new Date('2026-01-01T00:03:00Z') }); await store.createPreview({ token:'once', signalId:1, expiresAt:new Date('2026-01-01T00:02:00Z'), symbol:'BTCUSDT', marketType:'perpetual', longExchange:'extended', shortExchange:'risex', limitExchange:'risex', marketExchange:'extended', quantityBase:'1', longPriceUsd:'1', shortPriceUsd:'2', makerFeeBps:'1', takerFeeBps:'1' }); await assert.rejects(() => service.confirm('once'), /expired/); });

test('market hedge failure rolls back filled exposure once', async () => {
  const store = memoryStore(); const urgent: string[] = []; const risex = fakeAdapter('risex','100010','100020','0.001'); const extended = fakeAdapter('extended','99990','100000','0.0001'); const cancelled: string[] = []; const originalCancel = extended.execution!.cancelExecutionOrder; extended.execution!.cancelExecutionOrder = async id => { cancelled.push(id); await originalCancel(id); }; risex.execution!.submitExecutionOrder = async input => { risex.calls.push(input); if (input.type === 'market' && !input.reduceOnly) throw new Error('hedge failed'); return { id: `x-${risex.calls.length}`, status:'filled', filledQuantityBase:input.quantityBase, averageFillPriceUsd:'100020' }; };
  const service = new OpenTradeService(registry(risex,extended),store,{...options(),notifyUrgent:async text=>{urgent.push(text);}}); const p = await service.createPreview({signalId:1,symbol:'BTCUSDT',marketType:'perpetual',exchanges:['risex','extended']}); await assert.rejects(()=>service.confirm(p.token),/hedge failed/); assert.ok(cancelled.includes('limit')); assert.equal(extended.calls.filter(x=>x.reduceOnly && x.type==='market').length,1); assert.equal(risex.calls.filter(x=>x.reduceOnly && x.type==='market').length,1); assert.equal(store.states.at(-1),'failed'); assert.equal(urgent.length,1); const closes=extended.calls.filter(x=>x.reduceOnly).length+risex.calls.filter(x=>x.reduceOnly).length; await assert.rejects(()=>service.confirm(p.token)); assert.equal(extended.calls.filter(x=>x.reduceOnly).length+risex.calls.filter(x=>x.reduceOnly).length,closes);
});

test('protection failure cancels known protection and rolls back once', async () => {
  const store = memoryStore(); const urgent: string[]=[]; const risex=fakeAdapter('risex','100010','100020','0.001'); const extended=fakeAdapter('extended','99990','100000','0.0001'); const cancelled:string[]=[]; const original=extended.execution!.submitExecutionOrder; extended.execution!.submitExecutionOrder=async input=>{ if(input.type==='stop-market'){ extended.calls.push(input); throw new Error('SL rejected'); } return original(input); }; const originalCancel=extended.execution!.cancelExecutionOrder; extended.execution!.cancelExecutionOrder=async id=>{cancelled.push(id); await originalCancel(id);}; const service=new OpenTradeService(registry(risex,extended),store,{...options(),notifyUrgent:async text=>{urgent.push(text);}}); const p=await service.createPreview({signalId:1,symbol:'BTCUSDT',marketType:'perpetual',exchanges:['risex','extended']}); await assert.rejects(()=>service.confirm(p.token),/SL rejected/); assert.ok(cancelled.some(id=>id.startsWith('m-'))); assert.equal(extended.calls.filter(x=>x.reduceOnly&&x.type==='market').length,1); assert.equal(risex.calls.filter(x=>x.reduceOnly&&x.type==='market').length,1); assert.equal(store.states.at(-1),'failed'); assert.equal(urgent.length,1); const closes=extended.calls.filter(x=>x.reduceOnly).length+risex.calls.filter(x=>x.reduceOnly).length; await assert.rejects(()=>service.confirm(p.token)); assert.equal(extended.calls.filter(x=>x.reduceOnly).length+risex.calls.filter(x=>x.reduceOnly).length,closes);
});

function options() { return { notionalUsd:'1000', leverage:3, ttlMs:120000, quoteMaxAgeMs:5000, limitTimeoutMs:30000, residualDeltaToleranceBase:'0.00001', takeProfitPercent:'3', stopLossPercent:'3', fees:{ risex:{makerBps:'2',takerBps:'3'}, extended:{makerBps:'1',takerBps:'2'}, arcus:{makerBps:'0',takerBps:'0'} } }; }
function registry(...adapters: ExchangeAdapter[]) { return { get: (id: string) => { const adapter = adapters.find(x => x.id === id); if (!adapter) throw new Error('missing'); return adapter; } }; }
function fakeAdapter(id: 'risex'|'extended', bid: string, ask: string, step: string, orderStates = [{ status:'filled', filledQuantityBase:'999', averageFillPriceUsd: ask }]) { const calls: any[] = []; let n = 0; const adapter: ExchangeAdapter & { calls: any[] } = { id, displayName:id, capabilities:{nativeFetch:true,websocket:'polling-only',orderPlacement:true}, getMarkets:async()=>[], getPriceSnapshot:async()=>({} as any), calls, execution:{ getBestBidOffer:async()=>({bidUsd:bid,askUsd:ask,receivedAt:new Date()}), getMarketMetadata:async()=>({minQuantityBase:step,quantityStepBase:step}), getAvailableMarginUsd:async()=> '99999', validateExecutionPreflight:async()=>undefined, submitExecutionOrder:async(input)=>{ calls.push(input); if (input.type !== 'limit') return {id:`m-${calls.length}`,status:'filled',filledQuantityBase:input.quantityBase,averageFillPriceUsd:ask}; return {id:'limit',...orderStates[0]}; }, getExecutionOrder:async()=>orderStates[Math.min(++n, orderStates.length-1)]!, cancelExecutionOrder:async()=>undefined, getPosition:async()=>null } }; return adapter; }
function memoryStore(): PreviewStore & { states: OpenTradeState[] } { const previews = new Map<string, OpenTradePreview>(); const states: OpenTradeState[] = []; let rollback = false; return { states, async createPreview(p) { previews.set(p.token,p); }, async consumePreview(token, now) { const p=previews.get(token); if (!p || p.expiresAt <= now) return null; previews.delete(token); return p; }, async startExecution() { states.push('executing_limit'); }, async claimRollback() { if (rollback) return false; rollback = true; return true; }, async transition(_token,state) { states.push(state); } }; }
